name: excel2arb
description: A Dart package that allows you to download an Excel file from a given URL and generate ARB (Application Resource Bundle) files.
version: 1.0.0
repository: https://github.com/toe-lie/excel_to_arb_generator

executables:
  excel2arb:

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  excel: ^2.1.0
  http: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.6
